spring:
  data:
    mongodb:
      database: Student
      uri: mongodb+srv://deepak:1234sonu@cluster0.fvcgi.mongodb.net/Student?retryWrites=true&w=majority


      auto-index-creation: true

server:
  port: 8081

#logging:
#  level:
#    root: off
