spring:
  profiles:
    active: pro






  mail:
          host:xxxxxxxxxxx
          port:xxxxx

          username: xxxxxxxxxxxxxxxxxxxx
          password: xxxxxxxxxxxxxxxxxxxx
          properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
  data:
    redis:
      host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxxx
#      host:xxxxxx
#      port:xxxx



weather:
  api:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxx

