spring:
  data:
    mongodb:
      database: Student
      uri:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


      auto-index-creation: true

server:
  port: xxxx

#logging:
#  level:
#    root: off
